In [5]:
# 넘파이(NumPy)는 파이썬에서 수치 데이터를 효과적이고 빠르게 처리할 수 있도록 지원하는 라이브러리(통계분석, 데이터 분석 및 머신러닝 분야)

In [2]:
import numpy as np   # NumPy 기능 쓰기 위해 불러오기

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])      # Array(배열) : 동일한 데이터 타입을 가진 요소들을 모아서 저장한 자료구조

In [4]:
a.shape    # Shape :  배열(array)의 모양 또는 구조 / 위 array는 2개의 행(row)과 3개의 열(column)

(2, 3)

In [ ]:
# Array fundamentals

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])

In [7]:
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a[0]

np.int64(1)

In [9]:
a[0] = 10   # 덮어쓰는 기능

In [10]:
a

array([10,  2,  3,  4,  5,  6])

In [11]:
a[:3]      # Slice / 처음부터 인덱스 3 직전(즉, 인덱스 0, 1, 2) 까지의 요소를 가져오기

array([10,  2,  3])

In [12]:
b = a[3:]   # Slice / 처음부터 인덱스 3부터 끝까지 요소 다 가져오기

In [13]:
b

array([4, 5, 6])

In [14]:
b[0] = 40

In [15]:
a

array([10,  2,  3, 40,  5,  6])

In [16]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [17]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
a[1, 3]      # 첫 번째 인덱스 (1) : 두 번째 행을 나타냄 (인덱스는 0부터 시작하므로), 두 번째 인덱스 (3) : 네 번째 열을 나타냄

np.int64(8)

In [20]:
# Array attributes

In [21]:
a.ndim    # .ndim은 넘파이 배열 a의 차원 수를 알려주는 속성 / 행과 열로 구성되어 있으므로 차원 수는 2임

2

In [22]:
a.shape   # 3개의 행(가로), 4개의 열(세로)

(3, 4)

In [23]:
len(a.shape) == a.ndim

True

In [24]:
a.size

12

In [27]:
import math
a.size == math.prod(a.shape)

True

In [28]:
a.dtype

dtype('int64')

In [29]:
# How to create a basic array

In [30]:
np.zeros(2)

array([0., 0.])

In [31]:
np.ones(2)    # 길이가 2인 1차원 배열을 만들고, 모든 값을 1로 채움

array([1., 1.])

In [32]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [33]:
np.arange(4)

array([0, 1, 2, 3])

In [34]:
np.arange(2, 9, 2)   # first number, last number, and the step size.

array([2, 4, 6, 8])

In [35]:
np.linspace(0, 10, num=5)      # 0부터 10까지를 동일한 간격으로 나눈 5개의 숫자 (주의 : linspace는 10도 포함임)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
x = np.ones(2, dtype=np.int64)   # 배열의 데이터 타입을 64비트 정수 (int64)로 지정

In [37]:
x

array([1, 1])

In [38]:
# Adding, removing, and sorting elements

In [39]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [40]:
np.sort(arr)     # np.sort() (원본은 유지, 정렬된 복사본 반환)   VS

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)      # axis=0: 행 방향으로 추가 (행 개수 증가, 열 개수는 같아야 함)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
# How do you know the shape and size of an array?

In [51]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [52]:
array_example.ndim   # 3차원

3

In [53]:
array_example.size

24

In [54]:
array_example.shape   # 층(=depth): 3개 / 각 층에 행: 2개 / 각 행에 열: 4개 => (3개 층, 각각 2개 행, 각각 4개 열)

(3, 2, 4)

In [55]:
# Can you reshape an array?

In [56]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [59]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [61]:
# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [62]:
a = np.array([1, 2, 3, 4, 5, 6])    # [1, 2, 3, 4, 5, 6]는 1차원 배열임. 그냥 요소 6개 (6,) VS [[1, 2, 3, 4, 5, 6]]는 2차원 배열임(행이 1개, 열이 6개)(1,6)
a.shape

(6,)

In [65]:
a2 = a[np.newaxis, :]         # 1차원을 2차원으로 바뀌주는 방법인
a2
a2.shape

(1, 6)

In [66]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [67]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [68]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [69]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [70]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [71]:
# Indexing and slicing

In [72]:
data = np.array([1, 2, 3])

In [73]:
data[1]

np.int64(2)

In [74]:
data[0:2]

array([1, 2])

In [75]:
data[1:]

array([2, 3])

In [76]:
data[-2:]

array([2, 3])

In [77]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [78]:
print(a[a < 5])

[1 2 3 4]


In [79]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [80]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [81]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [82]:
five_up = (a > 5) | (a == 5)          # | → 논리적 OR (둘 중 하나라도 True면 True)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [86]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)        # np.nonzero(condition)은 **조건이 True인 위치(인덱스)**를 튜플 형태로 반환
print(b)                     # 첫 번째 배열: 행 인덱스들, 두 번째 배열: 열 인덱스들

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [87]:
# [[ True  True  True  True]
#  [False False False False]
#  [False False False False]] 이니까, a[0,0], a[0,1], a[0,2], a[0,3]만 조건 만족. 이걸 행별로, 열별로 풀어놓은거임

In [89]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [90]:
print(a[b])

[1 2 3 4]


In [91]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [92]:
# How to create an array from existing data

In [93]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [95]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [96]:
np.vstack((a1, a2))   # np.vstack(())은 수직으로 쌓기

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [97]:
np.hstack((a1, a2))  # np.hstack(())은 수평으로 쌓기

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [98]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [99]:
np.hsplit(x, 3)       # np.hsplit(a, n)	열을 기준으로 n개로 균등 분할

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [100]:
np.hsplit(x, (3, 4))    # np.hsplit(a, (i, j))	i, j열 위치 기준으로 쪼갬 / 3번째 열에서 쪼개고, 4번째 열에서 또 쪼갬

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [101]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [103]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [104]:
b2 = a.copy()

In [105]:
# Basic array operations

In [106]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)   # 얘의 값은 [1, 1] 이니까
data + ones   # plus(+)라면 1+1, 2+1

array([2, 3])

In [107]:
data - ones

array([0, 1])

In [108]:
data * data

array([1, 4])

In [109]:
data / data

array([1., 1.])

In [110]:
a = np.array([1, 2, 3, 4])
a.sum()

np.int64(10)

In [111]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)     # axis=0 = 열 단위 합 (세로 더함)

array([3, 3])

In [112]:
b.sum(axis=1)     # axis=1 = 행 단위 합 (가로 더함)

array([2, 4])

In [113]:
# Broadcasting

In [114]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [115]:
# More useful array operations

In [119]:
data.max()

np.float64(2.0)

In [120]:
data.min()

np.float64(1.0)

In [122]:
data.sum()

np.float64(3.0)

In [123]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [124]:
a.sum()

np.float64(4.8595784)

In [125]:
a.min()

np.float64(0.05093587)

In [126]:
a.min(axis=0)      # axis = 0은 세로!! 0은 세로 0은 세로!!! 열 기준 최소값 모음

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [127]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [128]:
# Creating matrices

In [129]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [130]:
data[0, 1]   # 첫번째 행, 2번째 열의 값이 뭐니?

np.int64(2)

In [131]:
data[1:3]   # 1번째부터 2번째 값이 뭐니?

array([[3, 4],
       [5, 6]])

In [132]:
data[0:2, 0]   # 1번째부터 2번째 값이 뭐니? 근데, 1번째 열에서  ★

array([1, 3])

In [133]:
data.max()

np.int64(6)

In [134]:
data.min()

np.int64(1)

In [135]:
data.sum()

np.int64(21)

In [136]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [137]:
data.max(axis=0)

array([5, 6])

In [138]:
data.max(axis=1)

array([2, 5, 6])

In [139]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [140]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [141]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [142]:
np.ones(3)

array([1., 1., 1.])

In [143]:
np.zeros(3)

array([0., 0., 0.])

In [144]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.14967659, 0.46506494, 0.53221753])

In [145]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [146]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [147]:
rng.random((3, 2)) 

array([[0.90452706, 0.72473893],
       [0.20401249, 0.42606278],
       [0.21295697, 0.56146697]])

In [148]:
# Generating random numbers

In [149]:
rng.integers(5, size=(2, 4))    # 0부터 4 사이의 임의의 수를 2개의 행, 4개의 열로 만들어줘

array([[3, 4, 1, 2],
       [2, 0, 4, 3]])

In [150]:
# How to get unique items and counts

In [151]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [152]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [153]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [154]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [155]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [156]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [157]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [158]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [159]:
print(indices)

[0 1 2]


In [160]:
print(occurrence_count)

[2 1 1]


In [161]:
# Transposing and reshaping a matrix

In [162]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [164]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [165]:
arr.transpose()   #  행 열 바꾸기

array([[0, 3],
       [1, 4],
       [2, 5]])

In [166]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [167]:
# How to reverse an array

In [168]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [169]:
reversed_arr = np.flip(arr)

In [170]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [171]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [172]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [173]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [174]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [175]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [176]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [177]:
# Reshaping and flattening multidimensional arrays

In [181]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [179]:
x.flatten()    # flatten()은 1차원으로 평면화

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [180]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array (flatten했다고 해서 원래 값이 바뀌진 않음)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [182]:
print(a1)  # New array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [185]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [186]:
print(a2)     # rabel을 사용하면 원래 값도 바껴버림

[98  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# 즉, flatten()은 복사(copy)본을 반환하고, ravel()은 가능한 경우 뷰(view, 원본 공유)를 반환